### ISSUE TITLE
Console errors invalid key in validation rule 

### ISSUE THREAD

**Issue by kikoseijo** [zollero/el-search-table-pagination#4]
Got this errors, 

![screen shot 2017-12-17 at 12 22 27](https://user-images.githubusercontent.com/1528668/34079901-67838b54-e336-11e7-8549-39a0bee86abb.png)

I resolved the promise using the fetch.

**Comment by zollero** [comment]
@kikoseijo ok. This errors do not appear in my project. I will check this.

**Comment by kikoseijo** [comment]
If this helps

![screen shot 2017-12-17 at 16 41 44](https://user-images.githubusercontent.com/1528668/34081137-37550814-e349-11e7-9d80-8859c3cc9a5f.png)

**Comment by zollero** [comment]
@kikoseijo I figure it out, the reason is the prop validation in Vue v2.5.10 validates the key out of `['type', 'default', 'required', 'validator']` invalid. Check [this commit](https://github.com/vuejs/vue/pull/7198/commits/e2a2a7a4a8418fec8a9693278c202d9096914388)

And the whole validation code:
![image](https://user-images.githubusercontent.com/8801894/34086514-4bd52e84-e3d7-11e7-809b-5f5ed74b59e4.png)

So, you must using Vue v2.5.10 or higher version. 

I will change the prop validation in `el-search-table-pagination` soon, and release it in the next version.

**Comment by zollero** [comment]
Or you can go back to the previous version of vuejs (2.5.10).

**Comment by kikoseijo** [comment]
And you sort of dynamic loading, I see.
Glad you found, because won't look god to anyone if this errors rise all the time.

All the best.

**Comment by zollero** [comment]
@kikoseijo Just release v0.4.20, remove errors. Please know it.😆
